# @desc [Automation - Backup Cisco Router or Switch]
---
- name: Backup Cisco Router or Switch
  hosts: Cisco
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: all
    - name: Get current date
      local_action: command date +%Y-%b-%d
      register: date
    - name: Get current time
      local_action: command date +%H:%M
      register: time
    - name: Get running-config and save it
      ios_config:
       backup: yes
       backup_options:
         #ansible_host = getting device IP, ansible_net_hostname = getting device hostname
         filename: "{{ ansible_net_hostname }}_{{ ansible_host }}.cfg"
         #Every time create a new directory under named date and time
         dir_path: /backups/{{ date.stdout }}_at_{{ time.stdout }}
    - name: Tasks done
      debug: msg="All tasks has been done on {{ date.stdout }} at {{ time.stdout }}."
#End of codes